In [1]:

import numpy as np
arr1=np.array([1,2,23,4,5,6])
print(arr1)

[ 1  2 23  4  5  6]


In [2]:
print(np.shape(arr1))
arr1.reshape(6,1)


(6,)


array([[ 1],
       [ 2],
       [23],
       [ 4],
       [ 5],
       [ 6]])

In [3]:
print(arr1.ndim)


1


In [4]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
print(arr1.size)

6


In [7]:
print(arr1.dtype)

int32


In [8]:
print(arr1.itemsize)

4


In [9]:
arr3 = np.arange(1,6)
arr4 = np.arange(6,11)
print(arr3+arr4)
print(arr3-arr4)
print(arr3*arr4)
print(arr3/arr4)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [10]:
print(np.sqrt(arr3))
print(np.exp(arr3))
print(np.sin(arr3))
print(np.log(arr3))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [11]:
array = np.arange(1,13)
new_array = array.reshape((3,4))
print(new_array[0:,1:])
new_array[0,1:] = 100

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [12]:
data = np.arange(1,6)
mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data-mean )/std_dev
normalized_data
variance = np.var(data)

In [13]:
new_data = np.arange(1,12)
print(new_data>5)
new_data[(new_data>5)]
new_data[(new_data>5) & (new_data<10)]

[False False False False False  True  True  True  True  True  True]


array([6, 7, 8, 9])